version: '3'

services:
  redis:
    image: redis
    ports:
      - 6379:6379

  db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    env_file:
      - .env

  wkhtmltopdf:
    image: openlabs/docker-wkhtmltopdf-aas
    ports:
      - 8080:80
